# Generated by Django 3.0.3 on 2020-02-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unitprice', models.IntegerField()),
                ('production_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_users.Seller')),
            ],
        ),
    ]
